#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : ioport
Version  : 1.2
Release  : 1
URL      : https://people.redhat.com/rjones/ioport/files/ioport-1.2.tar.gz
Source0  : https://people.redhat.com/rjones/ioport/files/ioport-1.2.tar.gz
Summary  : Access I/O ports
Group    : Development/Tools
License  : GPL-2.0 GPL-2.0+
Requires: ioport-bin = %{version}-%{release}
Requires: ioport-license = %{version}-%{release}
Requires: ioport-man = %{version}-%{release}

%description
These commands enable command line and script access directly to I/O
ports on PC hardware.

The inb, inw and inl commands perform an input (read) operation on the
given I/O port, and print the result.

The outb, outw and outl commands perform an output (write) operation
to the given I/O port, sending the given data.  Note that the order of
the parameters is ADDRESS DATA.

The size of the operation is selected according to the suffix, with
'b' meaning byte, 'w' meaning word (16 bits) and 'l' meaning long
(32 bits).

%package bin
Summary: bin components for the ioport package.
Group: Binaries
Requires: ioport-license = %{version}-%{release}

%description bin
bin components for the ioport package.


%package license
Summary: license components for the ioport package.
Group: Default

%description license
license components for the ioport package.


%package man
Summary: man components for the ioport package.
Group: Default

%description man
man components for the ioport package.


%prep
%setup -q -n ioport-1.2
cd %{_builddir}/ioport-1.2

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1581639845
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FCFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=4 "
%configure --disable-static
make  %{?_smp_mflags}  -j1

%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make VERBOSE=1 V=1 %{?_smp_mflags} check

%install
export SOURCE_DATE_EPOCH=1581639845
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/ioport
cp %{_builddir}/ioport-1.2/COPYING %{buildroot}/usr/share/package-licenses/ioport/17e3b0eea99abffe6ac71e65627413236e0b117a
%make_install

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/inb
/usr/bin/inl
/usr/bin/inw
/usr/bin/outb
/usr/bin/outl
/usr/bin/outw

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/ioport/17e3b0eea99abffe6ac71e65627413236e0b117a

%files man
%defattr(0644,root,root,0755)
/usr/share/man/man1/inb.1
/usr/share/man/man1/inl.1
/usr/share/man/man1/inw.1
/usr/share/man/man1/outb.1
/usr/share/man/man1/outl.1
/usr/share/man/man1/outw.1
